name: siem
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - bottleneck
  - xarray
  - netcdf4
  - dask
  - ipython
  - cartopy
  - pytest
  - coverage
  - numpy
  - hdbscan
  - osmnx
  - pip
  - wrf-python
  - pip:
    - pseudonetcdf==3.1.0
